In [11]:
import pandas as pd

df = pd.read_csv("train.csv")

def transform_sex(s):
    if s == "female":
        return 0
    elif s == "male":
        return 1

df.Sex = df.Sex.map(transform_sex)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [12]:
import pandas as pd

df = pd.read_csv("train.csv")

# def transform_sex(s):
#     if s == "female":
#         return 0
#     elif s == "male":
#         return 1

df.Sex = df.Sex.map(lambda s: 1 if s == "male" else 0)
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [13]:
import pandas as pd

df = pd.read_csv("train.csv")

df.Sex = df.Sex.map({"female": 0, "male": 1})
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    1  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    0  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    0  35.0      1      0   
4                           Allen, Mr. William Henry    1  35.0      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S

In [35]:
df.Embarked.unique()
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [32]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import numpy as np

ohenc = OneHotEncoder()
lblenc = LabelEncoder()

# OneHotEncoder
vec = np.array(df.Embarked.dropna().map({"S": 0, "C": 1, "Q": 2}))
print(vec.shape)
vec = vec.reshape(-1, 1)
print(vec.shape)
ohenc.fit(vec)
new_embarked = ohenc.transform(vec)
new_embarked.todense()

(889,)
(889, 1)


matrix([[1., 0., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        ...,
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [24]:
import numpy as np
np.array([[0,0],[1,0]]).dot(np.ones((2,)))

array([0., 1.])

In [28]:
import sklearn

print(sklearn.__version__)

0.22.1


## Start preprocessing

In [44]:
import pandas as pd

df = pd.read_csv("train.csv")
# data = df.drop(columns=["PassengerId", "Name", "Ticket", "Cabin"])
data = df[["Survived", "Pclass", "Sex", "Age", "SibSp", "Parch", "Fare","Embarked"]]
data = data.dropna()

data.Sex = data.Sex.map({"female": 0, "male": 1})
data.Embarked = data.Embarked.map({"S": 0, "C": 1, "Q": 2})

# Standardize, PCA, Algo


data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         0
1         1       1    0  38.0      1      0  71.2833         1
2         1       3    0  26.0      0      0   7.9250         0
3         1       1    0  35.0      1      0  53.1000         0
4         0       3    1  35.0      0      0   8.0500         0

In [90]:
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA


# new_X = scale(data.drop(columns=["Survived"]))

# pca = PCA(n_components=4)
# new_X = pca.fit_transform(new_X)

Y_train = data["Survived"].iloc[0:500]
X_train = data.drop(columns=["Survived"]).iloc[0:500]
# X_train = new_X[0:500, :]
Y_test = data["Survived"].iloc[500:]
X_test = data.drop(columns=["Survived"]).iloc[500:]
# X_test = new_X[500:, :]



In [85]:
from sklearn.svm import SVC
from itertools import product

C_params = [0.2, 0.5, 1, 2, 5, 10, 25]
gamma_params = ["auto", "scale"]
kernel_params = ["linear", "rbf"]

for C, gamma, kernel in product(
    C_params, gamma_params, kernel_params): 
    cls = SVC(C=C, gamma=gamma, kernel=kernel)
    cls.fit(X_train, Y_train)
    score = cls.score(X_test, Y_test)
    print(f"C = {C}, gamma={gamma}, kernel={kernel} -> score = {score}")

C = 0.2, gamma=auto, kernel=linear -> score = 0.7783018867924528
C = 0.2, gamma=auto, kernel=rbf -> score = 0.8018867924528302
C = 0.2, gamma=scale, kernel=linear -> score = 0.7783018867924528
C = 0.2, gamma=scale, kernel=rbf -> score = 0.8018867924528302
C = 0.5, gamma=auto, kernel=linear -> score = 0.7783018867924528
C = 0.5, gamma=auto, kernel=rbf -> score = 0.8066037735849056
C = 0.5, gamma=scale, kernel=linear -> score = 0.7783018867924528
C = 0.5, gamma=scale, kernel=rbf -> score = 0.8113207547169812
C = 1, gamma=auto, kernel=linear -> score = 0.7783018867924528
C = 1, gamma=auto, kernel=rbf -> score = 0.8160377358490566
C = 1, gamma=scale, kernel=linear -> score = 0.7783018867924528
C = 1, gamma=scale, kernel=rbf -> score = 0.8160377358490566
C = 2, gamma=auto, kernel=linear -> score = 0.7783018867924528
C = 2, gamma=auto, kernel=rbf -> score = 0.8113207547169812
C = 2, gamma=scale, kernel=linear -> score = 0.7783018867924528
C = 2, gamma=scale, kernel=rbf -> score = 0.811320754

In [77]:
cls.predict(X_test)

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [78]:
Y_test

634    0
635    1
636    0
637    0
638    0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 212, dtype: int64

In [66]:
from sklearn.preprocessing import scale

new_X = scale(X)
X.describe()

Pclass         Sex         Age       SibSp       Parch        Fare  \
count  712.000000  712.000000  712.000000  712.000000  712.000000  712.000000   
mean     2.240169    0.636236   29.642093    0.514045    0.432584   34.567251   
std      0.836854    0.481420   14.492933    0.930692    0.854181   52.938648   
min      1.000000    0.000000    0.420000    0.000000    0.000000    0.000000   
25%      1.000000    0.000000   20.000000    0.000000    0.000000    8.050000   
50%      2.000000    1.000000   28.000000    0.000000    0.000000   15.645850   
75%      3.000000    1.000000   38.000000    1.000000    1.000000   33.000000   
max      3.000000    1.000000   80.000000    5.000000    6.000000  512.329200   

         Embarked  
count  712.000000  
mean     0.261236  
std      0.521561  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      0.000000  
max      2.000000

In [68]:
pd.DataFrame(new_X).describe()

0             1             2             3             4  \
count  7.120000e+02  7.120000e+02  7.120000e+02  7.120000e+02  7.120000e+02   
mean  -1.587369e-16  5.083325e-17  2.584933e-16  4.216353e-16 -1.372186e-17   
std    1.000703e+00  1.000703e+00  1.000703e+00  1.000703e+00  1.000703e+00   
min   -1.482983e+00 -1.322511e+00 -2.017717e+00 -5.527137e-01 -5.067874e-01   
25%   -1.482983e+00 -1.322511e+00 -6.657639e-01 -5.527137e-01 -5.067874e-01   
50%   -2.871914e-01  7.561375e-01 -1.133826e-01 -5.527137e-01 -5.067874e-01   
75%    9.085997e-01  7.561375e-01  5.770939e-01  5.225108e-01  6.647471e-01   
max    9.085997e-01  7.561375e-01  3.477095e+00  4.823409e+00  6.522419e+00   

                  5             6  
count  7.120000e+02  7.120000e+02  
mean  -6.221615e-17 -1.640386e-16  
std    1.000703e+00  1.000703e+00  
min   -6.534272e-01 -5.012257e-01  
25%   -5.012575e-01 -5.012257e-01  
50%   -3.576726e-01 -5.012257e-01  
75%   -2.962586e-02 -5.012257e-01  
max    9.031168e+00  3.336115e+00

In [79]:
from sklearn.decomposition import PCA

pca = PCA(n_components=4)
X2 = pca.fit_transform(new_X)



In [82]:
pca.components_
pca.explained_variance_

array([1.83286893, 1.74121499, 0.97947258, 0.86354071])

In [91]:
import xgboost as xgb
from itertools import product
from sklearn.metrics import accuracy_score

etas = [i*0.2 for i in range(1,5)]
depths = [4 + i**2 for i in range(1,4)]

for eta, depth in product(etas, depths): 
    cls = xgb.XGBClassifier(eta=eta, max_depth=depth)
    cls.fit(X_train, Y_train)
    Y_pred = cls.predict(X_test)
    score = accuracy_score(Y_test, Y_pred)
    print(f"eta = {eta}, depth={depth} -> score = {score}")

eta = 0.2, depth=5 -> score = 0.8443396226415094
eta = 0.2, depth=8 -> score = 0.839622641509434
eta = 0.2, depth=13 -> score = 0.8349056603773585
eta = 0.4, depth=5 -> score = 0.8443396226415094
eta = 0.4, depth=8 -> score = 0.839622641509434
eta = 0.4, depth=13 -> score = 0.8349056603773585
eta = 0.6000000000000001, depth=5 -> score = 0.8443396226415094
eta = 0.6000000000000001, depth=8 -> score = 0.839622641509434
eta = 0.6000000000000001, depth=13 -> score = 0.8349056603773585
eta = 0.8, depth=5 -> score = 0.8443396226415094
eta = 0.8, depth=8 -> score = 0.839622641509434
eta = 0.8, depth=13 -> score = 0.8349056603773585
